# Generated by Django 2.1.7 on 2019-11-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adpost',
            name='open_for_all',
            field=models.BooleanField(default=True),
        ),
    ]
