# Generated by Django 2.1.11 on 2019-11-23 22:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adit', '0002_adpost_open_for_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestedtags',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
