# Generated by Django 2.1.11 on 2019-11-24 23:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adit', '0003_adpost_view_by_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestedtags',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
