export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_UP = 'SIGN_UP';
export const GET_USER = 'GET_USER';
export const PUT_USER = 'PUT_USER';
export const PUT_POINT = 'PUT_POINT';
export const GET_HOTTEST_ARTICLE = 'GET_HOTTEST_ARTICLE';
export const GET_GRID_ARTICLE = 'GET_GRID_ARTICLE';
export const GET_RECENT_ARTICLE = 'GET_RECENT_ARTICLE';
export const GET_CUSTOM_ARTICLE = 'GET_CUSTOM_ARTICLE';
export const GET_LISTED_ARTICLE = 'GET_LISTED_ARTICLE';
export const GET_OWN_ARTICLE = 'GET_OWN_ARTICLE';
export const GET_PARTICIPATED_ARTICLE = 'GET_PARTICIPATED_ARTICLE';
export const GET_SEARCH_ARTICLE = 'GET_SEARCH_ARTICLE';
export const GET_DETAILED_ARTICLE = 'GET_DETAILED_ARTICLE';
export const POST_ARTICLE = 'POST_ARTICLE';
export const GET_ALL_TAG = 'GET_TAG';
export const GET_RECENT_TAG = 'GET_RECENT_TAG'
export const POST_RECEPTION = 'POST_RECEPTION';
export const GET_RECEPTION = 'GET_RECEPTION';
export const POST_TAG = 'POST_TAG';
export const GET_PARTICIPATED = 'GET_IF_PARTICIPATED';
export const GET_BYUSER = 'GET_BYUSER';
export const NOT_PARTICIPATED = 'NOT_PARTICIPATED';

export const GET_ADLIST_PENDING = 'GET_ADLIST_PENDING';
export const GET_ADLIST_SUCCESS = 'GET_ADLIST_SUCCESS';
export const GET_ADLIST_FAILURE = 'GET_ADLIST_FAILURE';

export const GET_DETAILED_ADPOST_PENDING = 'GET_DETAILED_ADPOST_PENDING';
export const GET_DETAILED_ADPOST_SUCCESS = 'GET_DETAILED_ADPOST_SUCCESS';
export const GET_DETAILED_ADPOST_FAILURE = 'GET_DETAILED_ADPOST_FAILURE';

export const POST_ADPOST_PENDING = 'POST_ADPOST_PENDING';
export const POST_ADPOST_SUCCESS = 'POST_ADPOST_SUCCESS';
export const POST_ADPOST_FAILURE = 'POST_ADPOST_FAILURE';
